# Check deleted node
#apiVersion: v1
#kind: Pod
#metadata:
#  labels:
#    nifi_cr: simplenifi
#    nodeId: '3'
#status:
#  phase: Terminating
#---
# Check Nificluster created
apiVersion: nifi.orange.com/v1alpha1
kind: NifiCluster
metadata:
  name: simplenifi
spec:
  nodes:
    - id: 0
      nodeConfigGroup: "default_group"
    - id: 1
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
status:
  state: ClusterRollingUpgrading
#---
#apiVersion: kuttl.dev/v1beta1
#kind: TestAssert
#commands:
#  # Test correct amount of pods
#  - command: '[[ $(kubectl get pods --selector=nifi_cr=simplenifi -n $NAMESPACE | wc -l) -eq 4 ]]'
