---
apiVersion: nifi.orange.com/v1alpha1
kind: NifiCluster
metadata:
  name: nifi-cluster
  namespace: nifi
spec:
  service:
    headlessEnabled: true
  zkAddress: 'zookeeper:2181'
  zkPath: '/simplenifi'
  clusterImage: 'apache/nifi:1.11.3'
  oneNifiNodePerNode: false
  managedAdminUsers:
    - identity: "ME@MY_DOMAIN.com"
      name: "admin"
  nodeConfigGroups:
    default_group:
      isNode: true
      storageConfigs:
        - mountPath: '/opt/nifi/nifi-current/logs'
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: 'gp2'
            resources:
              requests:
                storage: 10Gi
      serviceAccountName: "default"
      resourcesRequirements:
        limits:
          cpu: "0.5"
          memory: 2Gi
        requests:
          cpu: "0.5"
          memory: 2Gi
  nodes:
    - id: 1
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - type: "https"
        name: "https"
        containerPort: 8443
      - type: "cluster"
        name: "cluster"
        containerPort: 6007
      - type: "s2s"
        name: "s2s"
        containerPort: 10000
    sslSecrets:
      tlsSecretName: "nifi-staging-tls"
      create: true
      clusterScoped: true
      issuerRef:
        kind: ClusterIssuer
        name: nifi-issuer
  externalServices:
    - name: "nifi-cluster"
      spec:
        type: ClusterIP
        portConfigs:
          - port: 8443
            internalListenerName: "https"   
  readOnlyConfig:
    nifiProperties:
      webProxyHosts:
        - nifi.MY_DOMAIN.com:8443
      overrideConfigs: |
        nifi.security.user.oidc.discovery.url=https://sso.MY_DOMAIN.com/auth/realms/MY_REALM/.well-known/openid-configuration
        nifi.security.user.oidc.client.id=nifi
        nifi.security.user.oidc.client.secret=abcdefghijklmnop123456789
        nifi.security.identity.mapping.pattern.dn=CN=([^,]*)(?:, (?:O|OU)=.*)?
        nifi.security.identity.mapping.value.dn=$1
        nifi.security.identity.mapping.transform.dn=NONE
