apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  # Install Zookeeper
  - command: kubectl create ns zookeeper
    ignoreFailure: true
  - command: helm repo add bitnami https://charts.bitnami.com/bitnami
    ignoreFailure: true
  - command: helm install zookeeper bitnami/zookeeper --namespace=zookeeper --set resources.requests.memory=256Mi --set resources.requests.cpu=250m --set resources.limits.memory=256Mi --set resources.limits.cpu=250m --set global.storageClass=local-path --set networkPolicy.enabled=true --set replicaCount=3
    ignoreFailure: true

    # Install the operator
  #  TODO How to select correct image tag & version ?
  #    --version 0.6.0 \
  #    --set image.tag=0.6.0-selfmanager-implem \
  # TODO remove image tag
  - command: helm install nifikop ../../helm/nifikop --set image.tag=0.6.0-selfmanager-implem --set resources.requests.memory=1Gi --set resources.requests.cpu=250m --set resources.limits.memory=1Gi --set resources.limits.cpu=500m --set debug.enabled=true --set certManager.enabled=false --set namespaces={"$NAMESPACE"}
    namespaced: true

    # Install selfmanager CRD (TODO remove later)
  - command: kubectl apply -f selfmanager-crd.yaml
    ignoreFailure: true