---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@MY_DOMAIN.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          # EKS specific
          route53:
            region: us-east-2
        selector:
          dnsZones:
            - MY_DOMAIN.com