---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: example-cert
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 521
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
    group: cert-manager.io