apiVersion: nifi.orange.com/v1alpha1
kind: NifiDataflow
metadata:
  name: dataflow-lifecycle-dev
spec:
  parentProcessGroupID: "16cfd2ec-0174-1000-0000-00004b9b35cc"
  bucketId: "01ced6cc-0378-4893-9403-f6c70d080d4f"
  flowId: "8fefc874-0c93-4ce5-ba53-1672f0b59aaa"
  flowVersion: 4
  runOnce: true
  skipInvalidControllerService: true
  skipInvalidComponent: true
  clusterRef:
    name: nc
    namespace: nifikop
  registryClientRef:
    name: squidflow
    namespace: nifikop
  parameterContextRef:
    name: dataflow-lifecycle-dev
    namespace: nifikop
  updateStrategy: drop