# permissions for end users to edit nifiusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifiuser-editor-role
rules:
- apiGroups:
  - nifi.orange.com
  resources:
  - nifiusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.orange.com
  resources:
  - nifiusers/status
  verbs:
  - get
