# permissions for end users to view nifiparametercontexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifiparametercontext-viewer-role
rules:
- apiGroups:
  - nifi.orange.com
  resources:
  - nifiparametercontexts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nifi.orange.com
  resources:
  - nifiparametercontexts/status
  verbs:
  - get
