# permissions for end users to view nificlusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nificluster-viewer-role
rules:
- apiGroups:
  - nifi.orange.com
  resources:
  - nificlusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nifi.orange.com
  resources:
  - nificlusters/status
  verbs:
  - get
