# permissions for end users to edit nifiparametercontexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifiparametercontext-editor-role
rules:
- apiGroups:
  - nifi.orange.com
  resources:
  - nifiparametercontexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.orange.com
  resources:
  - nifiparametercontexts/status
  verbs:
  - get
