# permissions for end users to edit nifidataflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifidataflow-editor-role
rules:
- apiGroups:
  - nifi.orange.com
  resources:
  - nifidataflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.orange.com
  resources:
  - nifidataflows/status
  verbs:
  - get
