apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nifidataflows.nifi.orange.com
spec:
  group: nifi.orange.com
  names:
    kind: NifiDataflow
    listKind: NifiDataflowList
    plural: nifidataflows
    singular: nifidataflow
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Nifi Dataflow is the Schema for the nifi dataflow API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NifiDataflowSpec defines the desired state of NifiDataflow
            properties:
              bucketId:
                description: The UUID of the Bucket containing the flow.
                type: string
              clusterRef:
                description: ClusterReference states a reference to a cluster for
                  dataflow/registryclient/user provisioning
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                type: object
              flowId:
                description: The UUID of the flow to run.
                type: string
              flowVersion:
                description: The version of the flow to run, if not present or equals
                  to -1, then the latest version of flow will be used.
                format: int32
                type: integer
              parameterContextRef:
                description: Object that will be passed to the NiFi Flow as parameteres.
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                type: object
              parentProcessGroupID:
                description: T
                type: string
              registryClientRef:
                description: The id of the parent process group where you want to
                  deploy your dataflow, if not set deploy at root level
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                type: object
              runOnce:
                description: If the flow will be ran once or continuously checked
                type: boolean
              skipInvalidComponent:
                type: boolean
              skipInvalidControllerService:
                type: boolean
              updateStrategy:
                description: DataflowUpdateStrategy defines the type of strategy to
                  update a flow
                enum:
                - drop
                - drain
                type: string
            required:
            - bucketId
            - flowId
            - updateStrategy
            type: object
          status:
            description: NifiDataflowStatus defines the observed state of NifiDataflow
            properties:
              latestDropRequest:
                properties:
                  connectionId:
                    type: string
                  current:
                    description: The count and size of flow files currently queued.
                    type: string
                  currentCount:
                    description: The number of flow files currently queued.
                    format: int32
                    type: integer
                  currentSize:
                    description: The size of flow files currently queued in bytes.
                    format: int64
                    type: integer
                  dropped:
                    description: The count and size of flow files that have been dropped
                      thus far.
                    type: string
                  droppedCount:
                    description: The number of flow files that have been dropped thus
                      far.
                    format: int32
                    type: integer
                  droppedSize:
                    description: The size of flow files currently queued in bytes.
                    format: int64
                    type: integer
                  failureReason:
                    description: An explication of why the request failed, or null
                      if this request has not failed.
                    type: string
                  finished:
                    description: Whether the request has finished.
                    type: boolean
                  id:
                    description: The id for this drop request.
                    type: string
                  lastUpdated:
                    description: The last time this request was updated.
                    type: string
                  original:
                    description: The count and size of flow files to be dropped as
                      a result of this request.
                    type: string
                  originalCount:
                    description: The number of flow files to be dropped as a result
                      of this request.
                    format: int32
                    type: integer
                  originalSize:
                    description: The size of flow files to be dropped as a result
                      of this request in bytes.
                    format: int64
                    type: integer
                  percentCompleted:
                    description: The percentage complete of the request, between 0
                      and 100.
                    format: int32
                    type: integer
                  state:
                    description: The state of the request
                    type: string
                  uri:
                    description: The uri for this request.
                    type: string
                required:
                - connectionId
                - current
                - currentCount
                - currentSize
                - dropped
                - droppedCount
                - droppedSize
                - failureReason
                - finished
                - id
                - lastUpdated
                - original
                - originalCount
                - originalSize
                - percentCompleted
                - state
                - uri
                type: object
              latestUpdateRequest:
                properties:
                  complete:
                    description: Whether or not this request has completed.
                    type: boolean
                  failureReason:
                    description: An explication of why the request failed, or null
                      if this request has not failed.
                    type: string
                  id:
                    description: The id of the update request.
                    type: string
                  lastUpdated:
                    description: The last time this request was updated.
                    type: string
                  percentCompleted:
                    description: The percentage complete of the request, between 0
                      and 100.
                    format: int32
                    type: integer
                  state:
                    description: The state of the request
                    type: string
                  type:
                    description: Defines the type of versioned flow update request.
                    type: string
                  uri:
                    description: The uri for this request.
                    type: string
                required:
                - complete
                - failureReason
                - id
                - lastUpdated
                - percentCompleted
                - state
                - type
                - uri
                type: object
              processGroupID:
                description: Queued flow files Process Group ID
                type: string
              state:
                description: DataflowState defines the state of a NifiDataflow
                type: string
            required:
            - processGroupID
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
