apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nifiregistryclients.nifi.orange.com
spec:
  group: nifi.orange.com
  names:
    kind: NifiRegistryClient
    listKind: NifiRegistryClientList
    plural: nifiregistryclients
    singular: nifiregistryclient
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Nifi Registry Client is the Schema for the nifi registry client
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NifiRegistryClientSpec defines the desired state of NifiRegistryClient
          properties:
            clusterRef:
              description: contains the reference to the NifiCluster with the one
                the user is linked
              properties:
                name:
                  type: string
                namespace:
                  type: string
              required:
              - name
              type: object
            description:
              type: string
            uri:
              description: The URI of the NiFi registry that should be used for pulling
                the flow.
              type: string
          required:
          - clusterRef
          - uri
          type: object
        status:
          description: NifiRegistryClientStatus defines the observed state of NifiRegistryClient
          properties:
            id:
              description: Queued flow files The nifi registry client's id
              type: string
            version:
              description: The last nifi registry client revision version catched
              format: int64
              type: integer
          required:
          - id
          - version
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
