# kubectl create secret generic secret-params --from-literal=secret1=yop --from-literal=secret2=yep
apiVersion: nifi.orange.com/v1alpha1
kind: NifiParameterContext
metadata:
  name: dataflow-lifecycle-prod
spec:
  description: "Contains prod configuration"
  clusterRef:
    name: nc
    namespace: nifikop
  secretRefs:
    - name: secret-params-prod
      namespace: nifikop
  parameters:
    - name: value1
      value: prod1
      description: "First variable"
    - name: value2
      value: prod2
      description: "Second variable"
    - name: value3
      value: prod3
      description: "Third variable"
    - name: value4
      value: prod4
      description: "Fourth variable"