apiVersion: nifi.orange.com/v1alpha1
kind: NifiUser
metadata:
  name: user-test
spec:
  # Contains the reference to the NifiCluster with the one the registry client is linked.
  clusterRef:
    name: nc
    namespace: nifikop
  includeJKS: true
  createCert: false
#  accessPolicies: []

