apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nifi-registry
  name: nifi-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi-registry
  template:
    metadata:
      labels:
        app: nifi-registry
    spec:
      containers:
        - image: michalklempa/nifi-registry:latest
          imagePullPolicy: Always
          name: nifi-registry
          ports:
            - containerPort: 18080
              name: web-http
          env:
            - name: NIFI_REGISTRY_WEB_HTTP_PORT
              value: "18080"
            - name: FLOW_PROVIDER
              value: "git"
            - name: GIT_REMOTE_URL
              value: "https://gitlab.com/dataflow-service/squidflow/schemaregistry.git"
            - name: GIT_CHECKOUT_BRANCH
              value: "master"
            - name: FLOW_PROVIDER_GIT_FLOW_STORAGE_DIRECTORY
              value: "/opt/nifi-registry/schemaregistry"
            - name: FLOW_PROVIDER_GIT_REMOTE_TO_PUSH
              value: "origin"
            - name: FLOW_PROVIDER_GIT_REMOTE_ACCESS_USER
              value: "erdrix"
            - name: FLOW_PROVIDER_GIT_REMOTE_ACCESS_PASSWORD
              value: "Math1lde1611"
            - name: GIT_CONFIG_USER_NAME
              value: "Alexandre G."
            - name: GIT_CONFIG_USER_EMAIL
              value: "alexandre.guitton@orange.com"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nifi-registry-service
  name: nifi-registry-service
spec:
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
  selector:
    app: nifi-registry
  type: ClusterIP
