{{- if .Values.rbacEnable | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "nifikop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nifikop.name" . }}
{{- end}}
