{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "nifikop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if and .Values.serviceAccount .Values.serviceAccount.name}}
  name: {{ .Values.serviceAccount.name }}      
  {{- else }}
  name: {{ template "nifikop.name" . }}
  {{- end }}
{{- end }}
